In [1]:
import numpy as np

In [2]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.random.rand(2)

array([0.43851498, 0.89659355])

In [8]:
np.random.randn(2)

array([-0.03377545, -1.33262808])

In [10]:
aaa = np.random.randint(0,101,100)

In [11]:
aaa.max()

100

In [13]:
aaa.argmin()

89

In [14]:
aaa.reshape(10,10)

array([[ 84,  93,  25,  88,  91,  10,  30,  46,  72,  33],
       [ 21,   6,  51,  87,  68,  95,  18,  30,  56,  11],
       [ 11,  91,  94,  66,  59,  40,  51,  72,  48,  11],
       [ 62,  16,  99,  52,  97,   6,  43,  25,  24,  57],
       [ 23,  60,  33,  38,  64,  25,  67,  42,  21,  45],
       [ 87,  37,  49,   6,  81,  73,  68,  73,  40,  11],
       [ 44,   7,  15,  11,  15,  88,   8,  88,  16, 100],
       [ 41,  96,  56,  25,  64,  98,  77,  13,  71,  68],
       [ 71,  63,  83,  46,  53,  57,  73,  99,  97,   0],
       [ 91,   6,  22,  10,   3,   9,  74,   4,  95,  40]])

In [15]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))


In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[1:2, 1:]

array([[25, 30]])

In [18]:
arr2d = np.zeros((10,10))

In [19]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
arr2d[[2,3,4,5]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])